catalog/urls.py
from django.urls import path
from .views import contacts, IndexListView, ProductDetailView, BlogCreateView, BlogListView, BlogDetailView,\
    BlogUpdateView, BlogDeleteView
from .apps import MainConfig

app_name = MainConfig.name

urlpatterns = [
    path('catalog.contacts/', contacts, name='contacts'),
    path('', IndexListView.as_view(), name='index'),
    # path('<int:pk>catalog.product/', product, name='product'),
    path('product/<int:pk>/', ProductDetailView.as_view(), name='detail_product'),
    path('create/', BlogCreateView.as_view(), name='create_blog'),
    path('view/', BlogListView.as_view(), name='view_blog'),
    path('blog/<int:pk>/', BlogDetailView.as_view(), name='detail_blog'),
    path('edit/<int:pk>/', BlogUpdateView.as_view(), name='update_blog'),
    path('delete/<int:pk>/', BlogDeleteView.as_view(), name='delete_blog'),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('catalog.urls', namespace='catalog'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

catalog/models.py
from django.db import models


NULLABLE = {'blank': True, 'null': True}


class Category(models.Model):
    name = models.CharField(max_length=200, verbose_name='название товара')
    description = models.TextField(verbose_name='описание', **NULLABLE)

    def __str__(self):
        return f"{self.name}"

    class Meta:
        verbose_name = 'категория'
        verbose_name_plural = 'категории'


class Product(models.Model):
    name = models.CharField(max_length=200, verbose_name='название товара')
    description = models.TextField(verbose_name='описание', **NULLABLE)
    preview = models.ImageField(upload_to="imagines/",  verbose_name='изображение', **NULLABLE)
    category = models.ForeignKey(Category, on_delete=models.CASCADE, verbose_name='категории')
    price = models.IntegerField(verbose_name='цена')
    date_create = models.DateField(verbose_name='дата создания', auto_now_add=True, **NULLABLE)
    last_modified_date = models.DateField(verbose_name='дата последнего изменения', auto_now=True, **NULLABLE)

    def __str__(self):
        return f"{self.name} ({self.category}) - {self.description}"

    class Meta:
        verbose_name = 'продукт'
        verbose_name_plural = 'продукты'


class Blog(models.Model):
    title = models.CharField(max_length=200, verbose_name='название блога')
    slug = models.CharField(verbose_name='Альт.название', max_length=255, unique=True, **NULLABLE)
    body = models.TextField(verbose_name='контент', **NULLABLE)
    preview = models.ImageField(upload_to="imagines/", verbose_name='изображение', **NULLABLE)
    date_create = models.DateField(verbose_name='дата создания', auto_now_add=True)
    is_published = models.BooleanField(default=True, verbose_name='опубликовано')
    views_count = models.IntegerField(default=0, verbose_name='просмотры')

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'блог'

catalog/views.py
from django.shortcuts import render
from .models import Product, Category, Blog
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy, reverse
from pytils.translit import slugify


# def index(request):
#     context = {
#         'object_list': Product.objects.all()[:100],
#         'title': 'Продукты'
#     }
#     return render(request, 'catalog/index.html', context)


class IndexListView(ListView):
    model = Product
    template_name = 'catalog/index.html'


# def product(request, pk):
#     product_item = Product.objects.get(pk=pk)
#     context = {
#         'object_list': Product.objects.filter(pk=pk),
#         'title': f'{product_item.name}'
#     }
#     return render(request, 'catalog/product_detail.html', context)


class ProductDetailView(DetailView):
    model = Product


def contacts(request):
    context = {
        'title': 'Контакты'
    }
    if request.method == 'POST':
        name = request.POST.get('name')
        phone = request.POST.get('phone')
        message = request.POST.get('message')
        print(f"{name} - ({phone}): {message}")
    return render(request, 'catalog/contacts.html', context)


class BlogCreateView(CreateView):
    model = Blog
    fields = ('title', 'body', 'preview')
    success_url = reverse_lazy('catalog:view_blog')

    def form_valid(self, form):
        if form.is_valid():
            new_blog = form.save()
            new_blog.slug = slugify(new_blog.title)
            new_blog.save()

        return super().form_valid(form)


class BlogListView(ListView):
    model = Blog
    template_name = 'catalog/blog_list.html'

    def get_queryset(self, *args, **kwargs):
        queryset = super().get_queryset(*args, **kwargs)
        queryset = queryset.filter(is_published=True)
        return queryset


class BlogDetailView(DetailView):
    model = Blog

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        self.object.views_count += 1
        self.object.save()
        return self.object


class BlogUpdateView(UpdateView):
    model = Blog
    fields = ('title', 'body', 'preview')
    # success_url = reverse_lazy('catalog:view_blog')

    def form_valid(self, form):
        if form.is_valid():
            new_blog = form.save()
            new_blog.slug = slugify(new_blog.title)
            new_blog.save()

        return super().form_valid(form)

    def get_success_url(self):
        return reverse('catalog:detail_blog', args=[self.kwargs.get('pk')])


class BlogDeleteView(DeleteView):
    model = Blog
    success_url = reverse_lazy('catalog:view_blog')

catalog/templates/catalog/base.html
<!doctype html>
<html lang="ru">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{{ title }}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
</head>
<body>
<div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom box-shadow">
    <h5 class="my-0 mr-md-auto font-weight-normal">Skystore</h5>
    <nav class="ms-5">
        <a class="p-2 btn btn-outline-primary" href="{% url 'catalog:index' %}">Каталог</a>
        <a class="p-2 btn btn-outline-primary" href="{% url 'catalog:view_blog' %}">Блог</a>
        <a class="p-2 btn btn-outline-primary" href="{% url 'catalog:contacts' %}">Контакты</a>
    </nav>
</div>

<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">{{ title|title }}</h1>
</div>
<div class="container">
    {% block content %}
    {% endblock %}
    <footer class="pt-4 my-md-5 pt-md-5 border-top">
        <div class="row">
            <div class="col-12 col-md">
                SkyStore
                <small class="d-block mb-3 text-muted">&copy; 2023 - {% now 'Y' %}</small>
            </div>
            <div class="col-6 col-md">
                <h5>О нас</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="{% url 'catalog:contacts' %}">Контакты</a></li>
                </ul>
            </div>
        </div>
    </footer>
</div>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>

catalog/templates/catalog/blog_confirm_delete.html
{% extends 'catalog/base.html' %}
{% block content %}
{% load my_tags %}
<div class="col-12">
    <div class="row">
        <div class="col-6">
        <div class="card">
            <div class="card-body">
              <form method="post">
                {% csrf_token %}
                <p>Хотите удалить блог "{{ object.title }}"?</p>
                <button type="submit" class="btn btn-lg btn-block btn-outline-danger">Подтвердить</button>
                <a href="{% url 'catalog:view_blog' %}" class="btn btn-lg btn-block btn-outline-warning">Отмена</a>
              </form>
            </div>
        </div>
    </div>
    </div>
{% endblock %}

catalog/templates/catalog/blog_detail.html
{% extends 'catalog/base.html' %}
{% block content %}
{% load my_tags %}
<div class="row text-center">
    <div class="col-12">
        <div class="col-6">
        <img class="card-img-top" src="{{ object.preview|mymedia }}">
        <div class="card mb-4 box-shadow">
            <div class="card-body">
                <ul class="list-unstyled mt-3 mb-4 text-start m-3">
                    <h3 class="truncate">Содержание: {{ object.body }}</h3>
                    <h3>{{ object.slug }}</h3>
                    <h3>Дата появления: {{ object.date_create|mydate }}</h3>
                    <h3>Количество просмотров: {{ object.views_count }}</h3>
                </ul>
                <button type="button" class="btn btn-lg btn-block btn-outline-primary">Купить</button>
            </div>
        </div>
        </div>
    </div>
    </div>
{% endblock %}

catalog/templates/catalog/blog_form.html
{% extends 'catalog/base.html' %}
{% block content %}
{% load my_tags %}
<div class="col-12">
  <div class="row">
    <div class="col-6">
      <div class="card">
        <div class="card-body">
          <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="btn btn-lg btn-block btn-outline-success">Сохранить</button>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

catalog/templates/catalog/blog_list.html
{% extends 'catalog/base.html' %}
{% block content %}
{% load my_tags %}
<div class="col-12 mb-5">
    <a class="p-2 btn btn-outline-primary" href="{% url 'catalog:create_blog' %}">Добавить блог</a>
</div>
<div class="row text-center">
    {% for object in object_list %}
        <div class="col-3">
             <img class="card-img-top" src="{{ object.preview|mymedia }}">
            <div class="card mb-4 box-shadow">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal" >{{ object.title|title }}</h4>
                </div>
                <div class="card-body">
                    <a class="p-1 btn btn-outline-primary" href="{% url 'catalog:detail_blog' object.pk %}">Подробнее</a>
                    <a class="p-1 btn btn-outline-primary" href="{% url 'catalog:update_blog' object.pk %}">Изменить</a>
                    <a class="p-1 btn btn-outline-primary" href="{% url 'catalog:delete_blog' object.pk %}">Удалить</a>
                </div>
            </div>
        </div>
    {% endfor %}
    </div>
{% endblock %}

catalog/templates/catalog/contacts.html
{% extends 'catalog/base.html' %}
{% block content %}
    <div class="row text-start">

        <div class="col-lg-9 col-md-6 col-sm-12">
            <div class="card mb-4 box-shadow">
                <div class="card-body">
                    <table class="table table-striped">
                        <tr>
                            <td class="w-25">Страна</td>
                            <td>USA</td>
                        </tr>
                        <tr>
                            <td class="w-25">ИНН</td>
                            <td>91-1144442</td>
                        </tr>
                        <tr>
                            <td class="w-25">Адрес</td>
                            <td>Redmond,WA,98052-6399</td>
                        </tr>
                    </table>
                </div>
            </div>
        </div>
        <div class="col-lg-3 col-md-6 col-sm-12">
            <div class="card mb-4 box-shadow">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal">Свяжитесь с нами</h4>
                </div>
                <div class="card-body">
                    <form method="post">
                      {% csrf_token %}
                        <div class="mb-3">
                        <label for="name">Имя</label>
                        <input type="text" name="name" class="form-control" id="name" placeholder="Ваше имя" required>
                        </div>
                        <div class="mb-3">
                        <label for="phone">Телефон</label>
                        <input type="text" name="phone" class="form-control" id="phone" placeholder="Контактный телефон" required>
                        </div>
                        <div class="mb-3">
                        <label for="message">Сообщение</label>
                        <textarea name="message" class="form-control" id="message" placeholder="Ваше сообщение" required></textarea>
                        </div>
                        <div class="md-3">
                            <button type="submit" class="btn btn-lg btn-block btn-outline-primary">Отправить</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

catalog/templates/catalog/index.html
{% extends 'catalog/base.html' %}
{% block content %}
{% load my_tags %}
<div class="row text-center">
    {% for object in object_list %}
        <div class="col-3">
             <img class="card-img-top" src="{{ object.preview|mymedia }}">
            <div class="card mb-4 box-shadow">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal" >{{ object.name|title }}</h4>
                </div>
                <div class="card-body">
                    <a class="p-2 btn btn-outline-primary" href="{% url 'catalog:detail_product' object.pk %}">Подробнее</a>
                </div>
            </div>
        </div>
    {% endfor %}
    </div>
{% endblock %}

catalog/templates/catalog/product_detail.html
{% extends 'catalog/base.html' %}
{% block content %}
{% load my_tags %}
<div class="row text-center">
        <div class="col-12">
        <div class="col-6">
            <img class="card-img-top" src="{{ object.preview|mymedia }}">
            <div class="card mb-4 box-shadow">
                <div class="card-body">
                    <ul class="list-unstyled mt-3 mb-4 text-start m-3">
                        <h1>Цена: {{ object.price }} Р.</h1>
                        <h3 class="truncate">Описание: {{ object.description }}</h3>
                        <h3>Категория: {{ object.category }}</h3>
                        <h3>Дата появления: {{ object.date_create|mydate }}</h3>
                    </ul>
                    <button type="button" class="btn btn-lg btn-block btn-outline-primary">Купить</button>
                </div>
            </div>
        </div>
        </div>
        </div>
    </div>
{% endblock %}

catalog/templates/main/base.html
<!doctype html>
<html lang="ru">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{{ title }}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
</head>
<body>
<div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom box-shadow">
    <h5 class="my-0 mr-md-auto font-weight-normal">Skystore</h5>
    <nav class="ms-5">
        <a class="p-2 btn btn-outline-primary" href="{% url 'catalog:index' %}">Каталог</a>
        <a class="p-2 btn btn-outline-primary" href="{% url 'catalog:contacts' %}">Контакты</a>
    </nav>
</div>

<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">{{ title|title }}</h1>
</div>
<div class="container">
    {% block content %}
    {% endblock %}
    <footer class="pt-4 my-md-5 pt-md-5 border-top">
        <div class="row">
            <div class="col-12 col-md">
                SkyStore
                <small class="d-block mb-3 text-muted">&copy; 2023 - {% now 'Y' %}</small>
            </div>
            <div class="col-6 col-md">
                <h5>О нас</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="{% url 'catalog:contacts' %}">Контакты</a></li>
                </ul>
            </div>
        </div>
    </footer>
</div>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>

catalog/templates/main/contacts.html
{% extends 'main/base.html' %}
{% block content %}
    <div class="row text-start">

        <div class="col-lg-9 col-md-6 col-sm-12">
            <div class="card mb-4 box-shadow">
                <div class="card-body">
                    <table class="table table-striped">
                        <tr>
                            <td class="w-25">Страна</td>
                            <td>USA</td>
                        </tr>
                        <tr>
                            <td class="w-25">ИНН</td>
                            <td>91-1144442</td>
                        </tr>
                        <tr>
                            <td class="w-25">Адрес</td>
                            <td>Redmond,WA,98052-6399</td>
                        </tr>
                    </table>
                </div>
            </div>
        </div>
        <div class="col-lg-3 col-md-6 col-sm-12">
            <div class="card mb-4 box-shadow">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal">Свяжитесь с нами</h4>
                </div>
                <div class="card-body">
                    <form method="post">
                      {% csrf_token %}
                        <div class="mb-3">
                        <label for="name">Имя</label>
                        <input type="text" name="name" class="form-control" id="name" placeholder="Ваше имя" required>
                        </div>
                        <div class="mb-3">
                        <label for="phone">Телефон</label>
                        <input type="text" name="phone" class="form-control" id="phone" placeholder="Контактный телефон" required>
                        </div>
                        <div class="mb-3">
                        <label for="message">Сообщение</label>
                        <textarea name="message" class="form-control" id="message" placeholder="Ваше сообщение" required></textarea>
                        </div>
                        <div class="md-3">
                            <button type="submit" class="btn btn-lg btn-block btn-outline-primary">Отправить</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

catalog/templates/main/index.html
{% extends 'main/base.html' %}
{% block content %}
{% load my_tags %}
<div class="row text-center">
    {% for object in object_list %}
        <div class="col-3">
             <img class="card-img-top" src="{{ object.preview|mymedia }}">
            <div class="card mb-4 box-shadow">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal" >{{ object.name|title }}</h4>
                </div>
                <div class="card-body">
                    <a class="p-2 btn btn-outline-primary" href="{% url 'catalog:product' object.pk %}">Подробнее</a>
                </div>
            </div>
        </div>
    {% endfor %}
    </div>
{% endblock %}

catalog/templates/main/product.html
{% extends 'main/base.html' %}
{% block content %}
{% load my_tags %}
<div class="row text-center">
    {% for object in object_list %}
        <div class="col">
            <img class="card-img-top" src="{{ object.preview|mymedia }}">
            <div class="card mb-4 box-shadow">
                <div class="card-body">
                    <ul class="list-unstyled mt-3 mb-4 text-start m-3">
                        <h1>Цена: {{ object.price }} Р.</h1>
                        <h3 class="truncate">Описание: {{ object.description }}</h3>
                        <h3>Категория: {{ object.category }}</h3>
                        <h3>Дата появления: {{ object.date_create|mydate }}</h3>
                    </ul>
                    <button type="button" class="btn btn-lg btn-block btn-outline-primary">Купить</button>
                </div>
            </div>
        </div>
    {% endfor %}
    </div>
{% endblock %}